"""Enterprise Baseline

Revision ID: 97afa46aa224
Revises: 
Create Date: 2026-03-10 03:40:10.863310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97afa46aa224'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_batch_id'), 'processing_jobs', ['batch_id'], unique=True)
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_data_batch_id'), 'raw_data', ['batch_id'], unique=False)
    op.create_index('ix_raw_data_batch_row', 'raw_data', ['batch_id', 'row_index'], unique=False)
    op.create_index(op.f('ix_raw_data_id'), 'raw_data', ['id'], unique=False)
    op.create_index(op.f('ix_raw_data_raw_text'), 'raw_data', ['raw_text'], unique=False)
    op.create_table('rule_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_audit_id'), 'rule_audit', ['id'], unique=False)
    op.create_index(op.f('ix_rule_audit_rule_id'), 'rule_audit', ['rule_id'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    op.create_table('taxonomy_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition_expression', sa.Text(), nullable=True),
    sa.Column('condition_payload', sa.JSON(), nullable=True),
    sa.Column('l0', sa.String(length=255), nullable=True),
    sa.Column('l1', sa.String(length=255), nullable=True),
    sa.Column('l2', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_taxonomy_rules_active', 'taxonomy_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_taxonomy_rules_id'), 'taxonomy_rules', ['id'], unique=False)
    op.create_index('ix_taxonomy_rules_l0_l1_l2', 'taxonomy_rules', ['l0', 'l1', 'l2'], unique=False)
    op.create_index(op.f('ix_taxonomy_rules_name'), 'taxonomy_rules', ['name'], unique=False)
    op.create_table('classified_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('l0', sa.String(length=255), nullable=True),
    sa.Column('l1', sa.String(length=255), nullable=True),
    sa.Column('l2', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('vector_match_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['taxonomy_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classified_output_id'), 'classified_output', ['id'], unique=False)
    op.create_index(op.f('ix_classified_output_raw_data_id'), 'classified_output', ['raw_data_id'], unique=False)
    op.create_index('ix_classified_output_raw_rule', 'classified_output', ['raw_data_id', 'rule_id'], unique=False)
    op.create_index(op.f('ix_classified_output_rule_id'), 'classified_output', ['rule_id'], unique=False)
    op.create_index('ix_classified_output_status', 'classified_output', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classified_output_status', table_name='classified_output')
    op.drop_index(op.f('ix_classified_output_rule_id'), table_name='classified_output')
    op.drop_index('ix_classified_output_raw_rule', table_name='classified_output')
    op.drop_index(op.f('ix_classified_output_raw_data_id'), table_name='classified_output')
    op.drop_index(op.f('ix_classified_output_id'), table_name='classified_output')
    op.drop_table('classified_output')
    op.drop_index(op.f('ix_taxonomy_rules_name'), table_name='taxonomy_rules')
    op.drop_index('ix_taxonomy_rules_l0_l1_l2', table_name='taxonomy_rules')
    op.drop_index(op.f('ix_taxonomy_rules_id'), table_name='taxonomy_rules')
    op.drop_index('ix_taxonomy_rules_active', table_name='taxonomy_rules')
    op.drop_table('taxonomy_rules')
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_rule_audit_rule_id'), table_name='rule_audit')
    op.drop_index(op.f('ix_rule_audit_id'), table_name='rule_audit')
    op.drop_table('rule_audit')
    op.drop_index(op.f('ix_raw_data_raw_text'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_id'), table_name='raw_data')
    op.drop_index('ix_raw_data_batch_row', table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_batch_id'), table_name='raw_data')
    op.drop_table('raw_data')
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_batch_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    # ### end Alembic commands ###
